apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: custom-rules-sample1
    namespace: sample1
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress:
    - action: allow
      applications:
      - any
      name: custom-rules-sample1-ingress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: address
          op: =
          value: 172.30.16.124
        - key: domain
          op: =
          value: openshift-monitoring
        - key: label
          op: =
          value: app.kubernetes.io/component=prometheus
        - key: label
          op: =
          value: app.kubernetes.io/instance=k8s
        - key: label
          op: =
          value: app.kubernetes.io/name=prometheus
        - key: label
          op: =
          value: app.kubernetes.io/part-of=openshift-monitoring
        name: nv.ip.prometheus-k8s.openshift-monitoring
        original_name: ""
    - action: allow
      applications:
      - any
      name: custom-rules-sample1-ingress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: openshift-ingress
        - key: service
          op: =
          value: router-default.openshift-ingress
        name: nv.router-default.openshift-ingress
        original_name: ""
    - action: allow
      applications:
      - any
      name: custom-rules-sample1-ingress-2
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: sample1
        name: custom-rules-sample1
        original_name: ""
    - action: allow
      applications:
      - any
      name: custom-rules-sample1-ingress-3
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: external
        original_name: ""
    - action: deny
      applications:
      - any
      name: custom-rules-sample1-ingress-4
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: container
          op: =
          value: '*'
        name: containers
        original_name: ""
    process: []
    target:
      policymode: N/A
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: sample1
        name: custom-rules-sample1
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
